# Generated by Django 2.2.27 on 2022-03-29 13:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gari_wala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='insaan',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=250)),
                ('gari_walaName', models.CharField(default='', max_length=250)),
                ('email', models.EmailField(default='email', max_length=254)),
                ('city', models.CharField(default='', max_length=250)),
                ('country', models.CharField(default='', max_length=250)),
                ('insaanAddress', models.CharField(default='', max_length=250)),
                ('nic', models.IntegerField(default=0)),
                ('gari_walaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insaans', to='gari_wala.gari_wala')),
            ],
        ),
    ]
