# Generated by Django 2.2.27 on 2022-03-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insaan',
            name='dropLat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='insaan',
            name='dropLong',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='insaan',
            name='pickLat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='insaan',
            name='pickLong',
            field=models.FloatField(default=0),
        ),
    ]
