# Generated by Django 2.2.27 on 2022-03-29 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gari_wala',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=250)),
                ('city', models.CharField(default='', max_length=250)),
                ('country', models.CharField(default='', max_length=250)),
                ('gari_walaAddress', models.CharField(default='', max_length=250)),
                ('nic', models.IntegerField(default=0)),
                ('email', models.EmailField(default='email', max_length=254)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
